### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by IshetaBansal** [Femme-js/Hoaxify#1]
The Readme file can have more input and beautification to enhance the overall presentation of the project. If interested, please assign it to me. 
Thank you :)

**Comment by Femme-js** [comment]
Can beautify the readme.

**Comment by IshetaBansal** [comment]
> Can beautify the readme.

If you are interested, please assign the issue to me.
Thank you :)

**Comment by Femme-js** [comment]
Assigned! Complete within 4 days.

**Comment by Femme-js** [comment]
What's the update?

**Comment by IshetaBansal** [comment]
> What's the update?

Hi 
I don't know why but due to some glitch I didn't receive any of your comments on this issue until now. 
Which is why I was unaware of the fact that I had been assigned. 
Please give me some time work on this issue now. 
I apologize for the delay but there was perhaps some problem. 
Hope you understand :)

**Comment by Sloth-Panda** [comment]
May I work on this??

**Comment by Femme-js** [comment]
@IshetaBansal Have you done?

**Comment by Sloth-Panda** [comment]
Hey, assign this to me. I will do it and make the pr sooner.

**Comment by Sloth-Panda** [comment]
Hey, plz assign this to me

**Comment by Femme-js** [comment]
Yes! @Sloth-Panda! You too can work on this issue further.

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this.

**Comment by Sloth-Panda** [comment]
@Femme-js can you checkout out this  pr and also other prs?
