### ISSUE TITLE
Make a logo for Hoaxify. 

### ISSUE THREAD

**Issue by Femme-js** [Femme-js/Hoaxify#11]

**Comment by Khimit** [comment]
@Femme-js  I would like to work on this.
Can you please assign this to me??

**Comment by Femme-js** [comment]
Assigned

**Comment by Khimit** [comment]
@Femme-js any suggestions from your side, which one should we choose.....
![hoaxify1](https://user-images.githubusercontent.com/46605529/103447094-b59d4180-4cac-11eb-877d-af8418227822.PNG)
![hoaxify2](https://user-images.githubusercontent.com/46605529/103447097-b9c95f00-4cac-11eb-9f3e-c284dbf55875.PNG)
![hoaxify3](https://user-images.githubusercontent.com/46605529/103447100-be8e1300-4cac-11eb-82a6-4bd35521075f.PNG)
![hoaxify4](https://user-images.githubusercontent.com/46605529/103447103-c2219a00-4cac-11eb-88fb-8c3ab4f40904.PNG)
![hoaxify5](https://user-images.githubusercontent.com/46605529/103447105-c5b52100-4cac-11eb-9ebc-4cf60c9ff70b.PNG)
![hoaxify6](https://user-images.githubusercontent.com/46605529/103447110-ca79d500-4cac-11eb-89f5-5bb73b874907.PNG)

**Comment by Femme-js** [comment]
the first or third one, i guess choose any
