### ISSUE TITLE
Add Contributors.md file

### ISSUE THREAD

**Issue by muthuannamalai12** [Femme-js/Hoaxify#13]
Hai,
I would like to add Contributors.md file in your project in the form of a table and display a link to it in README.md

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by Femme-js** [comment]
Assigned! Complete within 4 days.

**Comment by muthuannamalai12** [comment]
> Assigned! Complete within 4 days.

Ok.Thank you for assigning it to me

**Comment by muthuannamalai12** [comment]
I have created a pull request.Kindly review it
