### ISSUE TITLE
Integrate welcome bot

### ISSUE THREAD

**Issue by muthuannamalai12** [Femme-js/Hoaxify#19]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

If you feel this is a great idea!
Please assign it to me.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by akrish4** [comment]
Hi @Femme-js 
Let me know if also can work on it ?

**Comment by Femme-js** [comment]
I will assign this issue to only one guy.

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it
