### ISSUE TITLE
README , CONTRIBUTION and CODE of CONDUCT FILE 

### ISSUE THREAD

**Issue by akrish4** [Femme-js/Hoaxify#2]
Hi @Femme-js 
I found that there is no contribution and code of conduct files in this repository so I would like work on this , I will create a contribution , code of conduct file and update readme file 
kindly assign me this issue , 
I would like to contribute in this issue

**Comment by Femme-js** [comment]
Hey @akrish4 
I have updated the work structure of the readme. Make readme look more attractive. Also, create a code of conduct file.

**Comment by akrish4** [comment]
> Hey @akrish4
> I have updated the work structure of the readme. Create a contribution and code of conduct file.

Thank you @Femme-js 
Kindly assign me this issue and also add the tags DWOC tag also to this issue since it is registered under DWOC

**Comment by akrish4** [comment]
Kindly assign me this issue and also pls add the tags DWOC tag also to this issue since it is registered under DWOC
@Femme-js

**Comment by aditisneh** [comment]
Hey , is the issue open. would like to work on Readme. Will add a banner to this.

**Comment by akrish4** [comment]
Hi @Femme-js 
I have worked on it and  Kindly do check it and merge it
Also please do add the `DWOC` and  `Level-2` labels also in the PR

**Comment by akrish4** [comment]
@Femme-js  

#9

**Comment by Femme-js** [comment]
> Hey , is the issue open. would like to work on Readme. Will add a banner to this.
I will open a new issue for this, if you like to work on that I can assign it to you.

**Comment by akrish4** [comment]
Issue resolved #9
