### ISSUE TITLE
ISSUE TEMPLATE AND PR TEMPLATE 

### ISSUE THREAD

**Issue by akrish4** [Femme-js/Hoaxify#20]
Hi @Femme-js 
Let me know if you are interested in adding a issue and pr template to this repository which makes the maintainer's work more easier , these issue templates will consist of all major guidlines through which the user who opens a issue or opens a pr need to follow those instruction 

you can check this below image @Femme-js 
![issue1](https://user-images.githubusercontent.com/61831021/103884277-5b650c00-5104-11eb-99ef-ce5373100829.PNG)

**Comment by Femme-js** [comment]
Cool! Work on it. (4 days)

**Comment by akrish4** [comment]
Hi @Femme-js 
Kindly do assign me

**Comment by Sloth-Panda** [comment]
Hey, can I do this

**Comment by akrish4** [comment]
#23  PR
