### ISSUE TITLE
Add a CNN model to classify fake news

### ISSUE THREAD

**Issue by vaishnavi-1** [Femme-js/Hoaxify#30]
I wanted to add a CNN model which will classify fake news and I will train the dataset from kaggle or I can also try on the dataset which is used in the repo. Should I start doing this @Femme-js ?

**Comment by Femme-js** [comment]
Sure! Assigned to you.

**Comment by Femme-js** [comment]
@vaishnavi-1 Are you working on this?

**Comment by vaishnavi-1** [comment]
> @vaishnavi-1 Are you working on this?

Yes, I was working  but it has not been done and I can't give much time as my exams are coming...If I will not do it by tomorrow then I will close the issue. Actually, I opened the issue in January....you responded very late and at this time I'm not free.
