### ISSUE TITLE
Adding a seperate line for admin in readme.md file and creating a Contributors table which updates automatically.

### ISSUE THREAD

**Issue by Swastik1710** [Femme-js/Hoaxify#34]
As of now , the Contributors table in the readme.md file is not up to date. Moreover one needs to update it manually each and every time. I wanna automate this by adding a new Contributors table which will update by itself.
Moreover , I wanna add a separate line to showcase the Project Admin if you want.

**Comment by Swastik1710** [comment]
Can you please assign this to me ?
Thanks.

**Comment by Femme-js** [comment]
Great!

**Comment by Swastik1710** [comment]
Hey @Femme-js , I've made a PR.
Please have a look,
