### ISSUE TITLE
Front End Development for the Website

### ISSUE THREAD

**Issue by Swastik1710** [Femme-js/Hoaxify#37]
**Is your feature request related to a problem? Please describe.**
----
Every awesome project needs to have a Website linked to it so it would be great to have one for Hoaxify.

**Describe the solution you'd like**
----
I want to add Web support to this project by creating a website for this.

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by Swastik1710** [comment]
Hey @Femme-js , please assign it to me so that I can go ahead.
Moreover , I'm thinking of using React for this.

**Comment by Swastik1710** [comment]
Also please do let me know what all pages to we need to have.
Imo it should have a home page, an About Us page ,a Contributors page and a page which does all the stuff related to background.

**Comment by Femme-js** [comment]
@Swastik1710 You can go ahead with making a front-end.

**Comment by Swastik1710** [comment]
Okay Sure.
Thanks a lot.
I'll get back to you in 3 days.

**Comment by Femme-js** [comment]
sure!

**Comment by Swastik1710** [comment]
Hey @Femme-js 
I've made a PR, please have a look.
#40
